### ISSUE TITLE
Left/Right buttons on image gallery don't work sometimes

### ISSUE THREAD

**Issue by arkteck** [FEC-Capstone-Zesus/rfe2204-FEC#66]
#### Description 
Not sure what causes it but sometimes the left/right buttons in the image gallery will not change the image to previous/next but instead will open the expanded view.

#### Screenshots (if ui based) 
![Jun-04-2022 11-43-26](https://user-images.githubusercontent.com/64213090/172013239-8cdab50e-2e58-4f09-b69b-961733e65f07.gif)

#### Files 
https://github.com/FEC-Capstone-Zesus/rfe2204-FEC/blob/b48b3f3595081ead4f433372e0df6bfead96fe74/client/src/components/overview/ImageGallery.jsx

#### To Reproduce 
Change product/style a few times and probably also click on different thumbnails.

**Comment by nelliott82** [comment]
Great find. Fixed it.
